#!/bin/bash


# run iqe-sym
lr=0.0003
n_epochs=400
python main.py \
    --relabel-rate 0.5 \
    --project-name completeExperiments \
    --dim-hidden-critic 176 \
    --lr-actor $lr \
    --lr-critic $lr \
    --n-init-episodes 200 \
    --env-name FetchReach \
    --loss-scale 1 \
    --eval-rollout-n-episodes 100 \
    --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 \
    --n-epochs $n_epochs --agent her --critic iqe --cuda \
    --save-dir experiments/baseline_new/ddpg/FetchPush/iqe_her_0.5 --seed 100 \
    --exp-name "her_0.5"



#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/iqe_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/iqe_her_0.5 --seed 300 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/iqe_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/iqe_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/iqe_her_0.5 --seed 300 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/iqe_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/iqe_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/iqe_her_0.5 --seed 300 --exp-name "her_0.5"

#wait

#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/iqe_sym_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/iqe_sym_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/iqe_sym_her_0.5 --seed 300 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/iqe_sym_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/iqe_sym_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/iqe_sym_her_0.5 --seed 300 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/iqe_sym_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/iqe_sym_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic iqe-sym  --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/iqe_sym_her_0.5 --seed 300 --exp-name "her_0.5"

#wait
#exit

#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/monolithic_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/monolithic_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPush --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchPush/monolithic_her_0.5 --seed 300 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/monolithic_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/monolithic_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchPick --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchPick/monolithic_her_0.5 --seed 300 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/monolithic_her_0.5 --seed 100 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/monolithic_her_0.5 --seed 200 --exp-name "her_0.5" &
#python main.py --relabel-rate 0.5 --wandb --project-name completeExperiments --use-default-normalizer --dim-hidden-critic 176 --lr-actor $lr --lr-critic $lr --n-init-episodes 200 --env-name FetchSlide --loss-scale 1 --eval-rollout-n-episodes 100 --n-cycles 50 --n-batches 50 --batch-size 256 --rollout-n-episodes 1 --n-epochs $n_epochs --agent her --critic monolithic  --cuda --save-dir experiments/baseline_new/ddpg/FetchSlide/monolithic_her_0.5 --seed 300 --exp-name "her_0.5"

#wait